[tasks.build]
description = "Build languager server to your system"
run = "CGO_ENABLED=0 go build -mod=vendor -o bin/quadlet-lsp"

[tasks.build_all]
description = "Make an offline release"
run = "goreleaser release --clean --skip=publish --skip=validate"

[tasks.test]
description = "Run unit tests"
run = "go test -race ./..."

[tasks.lint]
description = "Check linting"
run = "golangci-lint run --max-same-issues 0 --max-issues-per-linter  0 ./..."

[tools]
go = "1.25.5"
golangci-lint = "2.8.0"
goreleaser = "2.12.1"
mdbook = "0.5.2"
